/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cviceni;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.JSpinner;

/**
 *
 * @author ag
 */
public class Vzor extends javax.swing.JFrame {
    private int r,g,b;//slozky nahodne barvy
    /**
     * Creates new form Tecka
     */
    public Vzor() {
        initComponents();
        r = 0;
        g = 0;
        b = 0;
        System.out.println("Šířka: " + panelPlatno.getWidth());//pomocny vypis
        System.out.println("Výška: " + panelPlatno.getHeight());//pomocny vypis
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPlatno = new javax.swing.JPanel(){
            protected void paintComponent(Graphics g){
                super.paintComponent(g);
                //moje kreslici metoda
                kresli(g);
            }
        };
        spinnerRed = new javax.swing.JSpinner();
        labelRed = new javax.swing.JLabel();
        labelRed1 = new javax.swing.JLabel();
        spinnerGreen = new javax.swing.JSpinner();
        labelRed2 = new javax.swing.JLabel();
        spinnerBlue = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kreslení");

        panelPlatno.setBackground(new java.awt.Color(255, 255, 255));
        panelPlatno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelPlatno.setPreferredSize(new java.awt.Dimension(280, 250));

        javax.swing.GroupLayout panelPlatnoLayout = new javax.swing.GroupLayout(panelPlatno);
        panelPlatno.setLayout(panelPlatnoLayout);
        panelPlatnoLayout.setHorizontalGroup(
            panelPlatnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );
        panelPlatnoLayout.setVerticalGroup(
            panelPlatnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 248, Short.MAX_VALUE)
        );

        spinnerRed.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        spinnerRed.setModel(new javax.swing.SpinnerNumberModel(0, 0, 255, 1));
        spinnerRed.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerRedStateChanged(evt);
            }
        });

        labelRed.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelRed.setText("R:");

        labelRed1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelRed1.setText("G:");

        spinnerGreen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        spinnerGreen.setModel(new javax.swing.SpinnerNumberModel(0, 0, 255, 1));
        spinnerGreen.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerGreenStateChanged(evt);
            }
        });

        labelRed2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelRed2.setText("B:");

        spinnerBlue.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        spinnerBlue.setModel(new javax.swing.SpinnerNumberModel(0, 0, 255, 1));
        spinnerBlue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerBlueStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelRed)
                        .addGap(18, 18, 18)
                        .addComponent(spinnerRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelRed1)
                        .addGap(18, 18, 18)
                        .addComponent(spinnerGreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelRed2)
                        .addGap(18, 18, 18)
                        .addComponent(spinnerBlue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(panelPlatno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(panelPlatno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinnerRed, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelRed))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinnerGreen, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelRed1))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinnerBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelRed2))))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void spinnerRedStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerRedStateChanged
       //zisk textCisla
       r = prevodNaInt(spinnerRed);
       //prekresleni
       panelPlatno.repaint();
    }//GEN-LAST:event_spinnerRedStateChanged

    private void spinnerGreenStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerGreenStateChanged
       //zisk textCisla
       g = prevodNaInt(spinnerGreen);
       //prekresleni
       panelPlatno.repaint(); 
    }//GEN-LAST:event_spinnerGreenStateChanged

    private void spinnerBlueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerBlueStateChanged
      //zisk textCisla
       b = prevodNaInt(spinnerBlue);
       //prekresleni
       panelPlatno.repaint();  
    }//GEN-LAST:event_spinnerBlueStateChanged

public void kresli(Graphics gr){
    System.out.println("Kreslím!");
     //graficky kontext (objekt zodpovedny za vykreslovani) Graphics2D (pretypovani)
      Graphics2D gt = (Graphics2D)gr;
        //pomocna metoda pro vyhlazeni car a krivek
        Grafika.antialiasing(gt);
        //nastaveni tloustky cary tvaru
        gt.setStroke(new BasicStroke(10)); 
        //nastaveni barvy pro kresleni tvaru
        gt.setColor(new Color(r,g,b));
        //vykresleni tvaru pomoci metod drawXXXXXX napr drawLine(x1,y1,x2y2)
        gt.drawOval(40,25,200,200);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vzor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vzor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vzor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vzor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vzor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelRed;
    private javax.swing.JLabel labelRed1;
    private javax.swing.JLabel labelRed2;
    private javax.swing.JPanel panelPlatno;
    private javax.swing.JSpinner spinnerBlue;
    private javax.swing.JSpinner spinnerGreen;
    private javax.swing.JSpinner spinnerRed;
    // End of variables declaration//GEN-END:variables

    private int prevodNaInt(JSpinner spinner) {
       //metoda ziska text ze spinneru a prevede na int
       //chyby nejsou osetreny
       String hodnota = spinner.getValue().toString();
       return Integer.parseInt(hodnota);
    }

}
