/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cviceni;

import javax.swing.JOptionPane;


/**
 *
 * @author rasovsky
 */
public class DPH extends javax.swing.JFrame {

    /**
     * Creates new form DPH
     */
    public DPH() {
        initComponents();
        labelCenaDPH.setDisplayedMnemonic('c');
        labelCenaDPH.setLabelFor(textFieldCenaDPH);
        
        labelSazbaDPH.setDisplayedMnemonic('s');
        labelSazbaDPH.setLabelFor(textFieldSazbaDPH);
        
        buttonVypocti.setMnemonic('v');
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCenaDPH = new javax.swing.JLabel();
        textFieldCenaDPH = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        labelSazbaDPH = new javax.swing.JLabel();
        textFieldSazbaDPH = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        buttonVypocti = new javax.swing.JButton();
        labelCenaBezDPH = new javax.swing.JLabel();
        textFieldCenaBezDPH = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        labelDPH = new javax.swing.JLabel();
        textFieldDPH = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DPH");

        labelCenaDPH.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelCenaDPH.setText("Cena včetně DPH");

        textFieldCenaDPH.setBackground(new java.awt.Color(204, 204, 204));
        textFieldCenaDPH.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textFieldCenaDPH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Kč");

        labelSazbaDPH.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelSazbaDPH.setText("Sazba DPH");

        textFieldSazbaDPH.setBackground(new java.awt.Color(204, 204, 204));
        textFieldSazbaDPH.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textFieldSazbaDPH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("%");

        buttonVypocti.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonVypocti.setMnemonic('A');
        buttonVypocti.setText("Vypočti");
        buttonVypocti.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonVypocti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVypoctiActionPerformed(evt);
            }
        });

        labelCenaBezDPH.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelCenaBezDPH.setText("Cena bez DPH");

        textFieldCenaBezDPH.setEditable(false);
        textFieldCenaBezDPH.setBackground(new java.awt.Color(214, 217, 223));
        textFieldCenaBezDPH.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textFieldCenaBezDPH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Kč");

        labelDPH.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelDPH.setText("DPH");

        textFieldDPH.setBackground(new java.awt.Color(214, 217, 223));
        textFieldDPH.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textFieldDPH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Kč");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelCenaDPH)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textFieldCenaDPH, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelSazbaDPH)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(textFieldSazbaDPH, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelCenaBezDPH)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(textFieldCenaBezDPH, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(labelDPH)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(textFieldDPH, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(buttonVypocti, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCenaDPH)
                    .addComponent(textFieldCenaDPH, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSazbaDPH)
                    .addComponent(textFieldSazbaDPH, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(buttonVypocti, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCenaBezDPH)
                    .addComponent(textFieldCenaBezDPH, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDPH)
                    .addComponent(textFieldDPH, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonVypoctiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVypoctiActionPerformed
           try{
            //nacteni
            double cenaDPH = Double.parseDouble(textFieldCenaDPH.getText());
            double sazbaDPH = Double.parseDouble(textFieldSazbaDPH.getText());
            
            //vypocet
            double cenaBezDPH = cenaDPH/(1+sazbaDPH/100);
            double dph = cenaDPH - cenaBezDPH;        
            
            String s_cenaBezDPH = String.format("%,.2f", cenaBezDPH);
            String s_dph = String.format("%,.2f", dph);
            //zapis vysledku
            textFieldCenaBezDPH.setText(s_cenaBezDPH);
            textFieldDPH.setText(s_dph);
           } 
          catch(Exception ex){
              JOptionPane.showMessageDialog(this, "Zkontrolujte zadání!", "Chyba", JOptionPane.ERROR_MESSAGE);
          }  
            
    }//GEN-LAST:event_buttonVypoctiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DPH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DPH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DPH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DPH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DPH dph = new DPH();
                //dph.setFocusable(true);//focus na okno; ne na prvni textField
                dph.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonVypocti;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel labelCenaBezDPH;
    private javax.swing.JLabel labelCenaDPH;
    private javax.swing.JLabel labelDPH;
    private javax.swing.JLabel labelSazbaDPH;
    private javax.swing.JTextField textFieldCenaBezDPH;
    private javax.swing.JTextField textFieldCenaDPH;
    private javax.swing.JTextField textFieldDPH;
    private javax.swing.JTextField textFieldSazbaDPH;
    // End of variables declaration//GEN-END:variables

    
}
