/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cviceni;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics2D;
import javax.swing.JTextField;

/**
 *
 * @author ag
 */
public class Vzor extends javax.swing.JFrame {
    private Bod stred;
    private Bod levyHorni;
    private Bod levySpodni;
    private Bod pravyHorni;
    private Bod pravySpodni;
    private final Graphics2D g;
            
    /**
     * Creates new form Tecka
     */
    public Vzor() {
        initComponents();
        stred = new Bod(panelPlatno.getWidth()/2,panelPlatno.getHeight()/2);
        levyHorni = new Bod(0,0);
        levySpodni = new Bod(0,panelPlatno.getHeight());
        pravyHorni = new Bod(panelPlatno.getWidth(),0);
        pravySpodni = new Bod(panelPlatno.getWidth(),panelPlatno.getHeight());
        
        g = (Graphics2D)panelPlatno.getGraphics();
        Grafika.antialiasing(g);
        
        fieldX.setText(String.valueOf(stred.getX()));
        fieldY.setText(String.valueOf(stred.getY()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPlatno = new javax.swing.JPanel();
        labelX = new javax.swing.JLabel();
        fieldX = new javax.swing.JTextField();
        labelY = new javax.swing.JLabel();
        fieldY = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Střed");
        setResizable(false);

        panelPlatno.setBackground(new java.awt.Color(255, 255, 255));
        panelPlatno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelPlatno.setPreferredSize(new java.awt.Dimension(280, 250));

        javax.swing.GroupLayout panelPlatnoLayout = new javax.swing.GroupLayout(panelPlatno);
        panelPlatno.setLayout(panelPlatnoLayout);
        panelPlatnoLayout.setHorizontalGroup(
            panelPlatnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );
        panelPlatnoLayout.setVerticalGroup(
            panelPlatnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 248, Short.MAX_VALUE)
        );

        labelX.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelX.setText("X:");

        fieldX.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        fieldX.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fieldX.setName("X"); // NOI18N
        fieldX.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldXFocusLost(evt);
            }
        });

        labelY.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelY.setText("Y:");

        fieldY.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        fieldY.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fieldY.setName("Y"); // NOI18N
        fieldY.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldYFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelX)
                    .addComponent(labelY))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldY, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(fieldX))
                .addGap(18, 18, 18)
                .addComponent(panelPlatno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(panelPlatno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelX)
                            .addComponent(fieldX, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelY)
                            .addComponent(fieldY, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fieldXFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldXFocusLost
        int x = parsovaniX(fieldX);
        stred.setX(x);
        kresli();
    }//GEN-LAST:event_fieldXFocusLost

    private void fieldYFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldYFocusLost
        int y = parsovaniY(fieldY);
        stred.setY(y);
        kresli();
    }//GEN-LAST:event_fieldYFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vzor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vzor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vzor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vzor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vzor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldX;
    private javax.swing.JTextField fieldY;
    private javax.swing.JLabel labelX;
    private javax.swing.JLabel labelY;
    private javax.swing.JPanel panelPlatno;
    // End of variables declaration//GEN-END:variables


    private int parsovaniX(JTextField field) {
        int x = Integer.parseInt(field.getText());
           if(x < 0 || x > panelPlatno.getWidth()){
               fieldX.setText(String.valueOf(panelPlatno.getWidth()/2)); 
               return panelPlatno.getWidth()/2;
           } 
           else{
               return x;
           }
    }

    private int parsovaniY(JTextField field) {
        int y = Integer.parseInt(field.getText());
           if(y < 0 || y > panelPlatno.getHeight()){
               fieldY.setText(String.valueOf(panelPlatno.getHeight()/2)); 
               return panelPlatno.getHeight()/2;
           } 
           else{
               return y;
           }
    }

    private void kresli() {
        //priprava
        panelPlatno.paint(g);//nebo paint(g) prekresli platno
        
        //kresleni
        g.setStroke(new BasicStroke(3));
        g.setColor(Color.black);
        
        g.drawLine(levyHorni.getX(), levyHorni.getY(), stred.getX(), stred.getY());
        g.drawLine(pravyHorni.getX(), pravyHorni.getY(), stred.getX(), stred.getY());
        g.drawLine(levySpodni.getX(), levySpodni.getY(), stred.getX(), stred.getY());
        g.drawLine(pravySpodni.getX(), pravySpodni.getY(), stred.getX(), stred.getY());
    }

    
}
