/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cviceni;

import Nastroje.KontrolaKnihovna;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author rasovsky
 */
public class Firma extends javax.swing.JFrame {
    private final Evidence evidence;
    private OknoVypis okno;
    /**
     * Creates new form NewJFrame
     */
    public Firma() {
        initComponents();
        evidence = new Evidence();
        cvicnaEvidence();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupRadioPohlavi = new javax.swing.ButtonGroup();
        groupRadioStav = new javax.swing.ButtonGroup();
        labelJmeno = new javax.swing.JLabel();
        textFieldJmeno = new javax.swing.JTextField();
        textFieldVek = new javax.swing.JTextField();
        labelVek = new javax.swing.JLabel();
        panelRadioPohlavi = new javax.swing.JPanel();
        radioPohlaviMuz = new javax.swing.JRadioButton();
        radioPohlaviZena = new javax.swing.JRadioButton();
        panelRadioStav = new javax.swing.JPanel();
        radioStavSbod = new javax.swing.JRadioButton();
        radioStavZenat = new javax.swing.JRadioButton();
        radioStavRozveden = new javax.swing.JRadioButton();
        radioStavVdovec = new javax.swing.JRadioButton();
        buttonUloz = new javax.swing.JButton();
        buttonVypis = new javax.swing.JButton();
        butonAktualizuj = new javax.swing.JButton();
        buttonSmaz = new javax.swing.JButton();
        labelStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Evidence");

        labelJmeno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelJmeno.setText("Jméno:");

        textFieldJmeno.setBackground(new java.awt.Color(204, 204, 204));
        textFieldJmeno.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textFieldJmeno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        textFieldJmeno.setName("jméno"); // NOI18N

        textFieldVek.setBackground(new java.awt.Color(204, 204, 204));
        textFieldVek.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textFieldVek.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        textFieldVek.setName("věk"); // NOI18N

        labelVek.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelVek.setText("Věk:");

        panelRadioPohlavi.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "Pohlaví", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        panelRadioPohlavi.setName("pohlaví"); // NOI18N

        groupRadioPohlavi.add(radioPohlaviMuz);
        radioPohlaviMuz.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radioPohlaviMuz.setText("Muž");

        groupRadioPohlavi.add(radioPohlaviZena);
        radioPohlaviZena.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radioPohlaviZena.setText("Žena");

        javax.swing.GroupLayout panelRadioPohlaviLayout = new javax.swing.GroupLayout(panelRadioPohlavi);
        panelRadioPohlavi.setLayout(panelRadioPohlaviLayout);
        panelRadioPohlaviLayout.setHorizontalGroup(
            panelRadioPohlaviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRadioPohlaviLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRadioPohlaviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioPohlaviMuz)
                    .addComponent(radioPohlaviZena))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        panelRadioPohlaviLayout.setVerticalGroup(
            panelRadioPohlaviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRadioPohlaviLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioPohlaviMuz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioPohlaviZena)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRadioStav.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "Stav", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        panelRadioStav.setName("stav"); // NOI18N

        groupRadioStav.add(radioStavSbod);
        radioStavSbod.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radioStavSbod.setText("Svobodný/á");

        groupRadioStav.add(radioStavZenat);
        radioStavZenat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radioStavZenat.setText("Ženatý/vdaná");

        groupRadioStav.add(radioStavRozveden);
        radioStavRozveden.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radioStavRozveden.setText("Rozvedený/á");

        groupRadioStav.add(radioStavVdovec);
        radioStavVdovec.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radioStavVdovec.setText("Vdovec/vdova");

        javax.swing.GroupLayout panelRadioStavLayout = new javax.swing.GroupLayout(panelRadioStav);
        panelRadioStav.setLayout(panelRadioStavLayout);
        panelRadioStavLayout.setHorizontalGroup(
            panelRadioStavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRadioStavLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRadioStavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioStavSbod)
                    .addComponent(radioStavZenat)
                    .addComponent(radioStavRozveden)
                    .addComponent(radioStavVdovec))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panelRadioStavLayout.setVerticalGroup(
            panelRadioStavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRadioStavLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioStavSbod)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioStavZenat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioStavRozveden)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioStavVdovec)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        buttonUloz.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonUloz.setText("Odešli do databáze");
        buttonUloz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUlozActionPerformed(evt);
            }
        });

        buttonVypis.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonVypis.setText("Vypiš databázi");
        buttonVypis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVypisActionPerformed(evt);
            }
        });

        butonAktualizuj.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        butonAktualizuj.setText("Aktualizuj záznam");
        butonAktualizuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonAktualizujActionPerformed(evt);
            }
        });

        buttonSmaz.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonSmaz.setText("Smaž záznam");
        buttonSmaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSmazActionPerformed(evt);
            }
        });

        labelStatus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelStatus.setText("Stav:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonUloz, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butonAktualizuj, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonSmaz, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonVypis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(100, 100, 100))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panelRadioPohlavi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(panelRadioStav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelJmeno)
                                    .addComponent(labelVek))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textFieldVek, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldJmeno))))
                        .addContainerGap(27, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelStatus)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelJmeno)
                    .addComponent(textFieldJmeno, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelVek)
                    .addComponent(textFieldVek, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRadioStav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelRadioPohlavi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(buttonUloz, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonVypis, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(butonAktualizuj, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonSmaz, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelStatus)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonUlozActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUlozActionPerformed
        try {
            //kontrola vstupu a vytvoreni zamestnance + ulozeni do evidence
            kontrolaVstupu(evt.getActionCommand());
            //vymazani vsech polozek; vcetne radioButton
            vymazaniTextu();
            //Info do label oblasti
            labelStatus.setText("Stav: uloženo");
        } catch(Exception ex){
            labelStatus.setText("Stav:");
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Chyba", JOptionPane.ERROR_MESSAGE);
        }
        
        
        
    }//GEN-LAST:event_buttonUlozActionPerformed

    private void buttonVypisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVypisActionPerformed
         okno = OknoVypis.zobrazOkno();
         okno.vypisText(evidence.vypisEvidence());
    }//GEN-LAST:event_buttonVypisActionPerformed

    private void butonAktualizujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonAktualizujActionPerformed
        //stav tlacitka Vyber záznam
            //JOptionPane (navrat cislo zaznamu nebo nic)
            //nacist udaje z pole ArrayList<Zamestnanec> do textField a radioButtons
            //zakazat ostatni tlacitka + zmenit text na tlacitku
            //zmena stavu Aktualizuj
        //stav tlacitka Aktualizuj
            //kontrola vstupu *******
            //prepsani zaznamu v poli Evidence ******* => je potreba cislo polozky v poli
            //povoleni tlacitek + zmena textu tlacitka
            //zmena stavu na Vyber zaznam 
    }//GEN-LAST:event_butonAktualizujActionPerformed

    private void buttonSmazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSmazActionPerformed
         buttonVypis.doClick(); //otevře vypis
         //Nastaveni cestiny pro tlacitka
         nastaveniCestiny("Storno", "Ne", "OK", "Ano");
         //nastaveni JCheckbox a zprávy pro uživatele v JOptionPane
         JCheckBox smazVse = new JCheckBox("Chcete smazat vše?");
         String message = "\n Zadejte číslo zaměstnance pro smazání.";
         Object[] params = {smazVse,message}; //pole objektu, ktere se zobrazi v okne
         String cisloZamestnance = JOptionPane.showInputDialog(this, params, "Dialog", JOptionPane.QUESTION_MESSAGE);
         
         if(cisloZamestnance == null){
             //storno
             labelStatus.setText("Status:");
         }
         else if(smazVse.isSelected()){
             //smaz
             evidence.smazVsechnyZamestnance();
             labelStatus.setText("Status: Vše smazáno.");
             okno.vypisText("");
         }
         else{
            //neni vybrano smaz vse => ptam se na vyplneni cisla zamestnance
             //pokud je vyplneno resim spravnost int
             try{
                 Integer.parseInt(cisloZamestnance);
                 System.out.println("Posílám k vymazání");
                 //smazani záznamu z evidence
                 labelStatus.setText("Status: Smazán záznam.");
             }
             catch(NumberFormatException ex){
                 labelStatus.setText("Status:");
                 JOptionPane.showMessageDialog(this, "Není zadáno celé číslo!", "Chyba", JOptionPane.ERROR_MESSAGE);
             } 
         }  
    }//GEN-LAST:event_buttonSmazActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Firma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Firma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Firma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Firma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Firma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butonAktualizuj;
    private javax.swing.JButton buttonSmaz;
    private javax.swing.JButton buttonUloz;
    private javax.swing.JButton buttonVypis;
    private javax.swing.ButtonGroup groupRadioPohlavi;
    private javax.swing.ButtonGroup groupRadioStav;
    private javax.swing.JLabel labelJmeno;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JLabel labelVek;
    private javax.swing.JPanel panelRadioPohlavi;
    private javax.swing.JPanel panelRadioStav;
    private javax.swing.JRadioButton radioPohlaviMuz;
    private javax.swing.JRadioButton radioPohlaviZena;
    private javax.swing.JRadioButton radioStavRozveden;
    private javax.swing.JRadioButton radioStavSbod;
    private javax.swing.JRadioButton radioStavVdovec;
    private javax.swing.JRadioButton radioStavZenat;
    private javax.swing.JTextField textFieldJmeno;
    private javax.swing.JTextField textFieldVek;
    // End of variables declaration//GEN-END:variables

   private void kontrolaVstupu(String textTlacitka) throws Exception{
        //zjisteni jake tlacitko zamestnance
        //vytvoreni zamestnance (novy objekt + zarazeni do pole) nebo update (vyhledani v poli + prepis hodnot)
        
           //kontrola vstupu a nacteni hodnot
           String jmeno = KontrolaKnihovna.prazdnePole(textFieldJmeno);
           int vek = KontrolaKnihovna.textDoInt(textFieldVek);
           
           String pohlavi = KontrolaKnihovna.kontrolaRadio(panelRadioPohlavi);
           
           
           String stavPredUpravou = KontrolaKnihovna.kontrolaRadio(panelRadioStav);
           String stav = stavMuzZena(stavPredUpravou);//vrati stav odpovidajici pohlavi (zenaty nebo vdana)
           
           if(textTlacitka.equals("Odešli do databáze")){
             //ulozeni
             evidence.novyZamestnanec(jmeno, vek, pohlavi, stav);
           }
           else{
             //aktualizace  
             evidence.aktualizaceZamestnance(jmeno, vek, pohlavi, stav);
        }
        
    }

    private void vymazaniTextu() {
         textFieldJmeno.setText("");
         textFieldVek.setText("");
         groupRadioPohlavi.clearSelection();
         groupRadioStav.clearSelection();
    }

    private String stavMuzZena(String stav) {
        //cislo v groupRadioStav
        int lomitko = stav.indexOf("/");//pozice lomitka v textu (napr. zenaty/vdana)
        stav = stav.substring(0, lomitko);//vrati text pred lomitkem (napr. z zenaty/vdana vrati zenaty)
        
        if (radioPohlaviMuz.isSelected()){
            return stav; // vraci uz ziskany text pred lomitkem
        }
        else{
            //u zeny je nutne vratit text za lomitkem (vyuzijeme enumerator)
            int index = Stav.valueOf(stav).ordinal() + 4; //zjisti cislo v Enum (0-3), pokud se jedna o zenu => pricte +4 => ziskam poradi
            stav = Stav.values()[index].name(); //vrati text stavu odpovidajici zene
            return stav;
        }
    }
    
    private void nastaveniCestiny(String storno, String no, String ok, String yes) {
         UIManager.put("OptionPane.cancelButtonText", storno);
         UIManager.put("OptionPane.noButtonText", no);
         UIManager.put("OptionPane.okButtonText", ok);
         UIManager.put("OptionPane.yesButtonText", yes);
    }
    
    private void cvicnaEvidence() {
       //cvicni zamestnanci 
       evidence.novyZamestnanec("Novák Jan", 31, "muž", "ženatý");
       evidence.novyZamestnanec("Nováková Pavlína", 29, "žena", "vdaná");
       evidence.novyZamestnanec("Fantiš Karel", 45, "muž", "rozvedený");
    }
}
