/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cviceni;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.util.Random;
import javax.swing.ImageIcon;

/**
 *
 * @author ag
 */
public class Vzor extends javax.swing.JFrame {
    int sirkaPlatna, vyskaPlatna, sirkaImg, vyskaImg, index1, index2, xPosition;
    boolean hodnoceni;
    Color colorWin;
    Image[] images;
    int[][] vysledky;
    Image player1Img, player2Img;
    Random nahoda;
    
    /**
     * Creates new form Tecka
     */
    public Vzor() {   
        initComponents();
        
        sirkaPlatna = panelPlatno.getWidth();
        vyskaPlatna = panelPlatno.getHeight();
        System.out.println("Šířka: " + sirkaPlatna);//pomocny vypis
        System.out.println("Výška: " + vyskaPlatna);//pomocny vypis
        
        images = new Image[]{
                new ImageIcon("src/images/kamen.png").getImage(),
                new ImageIcon("src/images/nuzky.png").getImage(),
                new ImageIcon("src/images/papir.png").getImage(),
                new ImageIcon("src/images/nic.png").getImage()
        };
        
        vysledky = new int[][]{
                                {2,1,0}, //pristup k vysledkum index1index2 (00,01,02)
                                {0,2,1}, //pristup k vysledkum index1index2 (10,11,12)
                                {1,0,2}  //pristup k vysledkum index1index2 (20,21,22)
        };
        sirkaImg = images[0].getWidth(null);
        vyskaImg = images[0].getHeight(null);
        player1Img = images[0];
        player2Img = images[0];
        colorWin = new Color(100,200,100);
        nahoda = new Random(); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPlatno = new javax.swing.JPanel(){
            protected void paintComponent(Graphics g){
                super.paintComponent(g);
                //moje kreslici metoda
                kresli(g);
            }
        };
        tlacitkoLosuj = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kreslení");

        panelPlatno.setBackground(new java.awt.Color(255, 255, 255));
        panelPlatno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelPlatno.setPreferredSize(new java.awt.Dimension(280, 250));

        javax.swing.GroupLayout panelPlatnoLayout = new javax.swing.GroupLayout(panelPlatno);
        panelPlatno.setLayout(panelPlatnoLayout);
        panelPlatnoLayout.setHorizontalGroup(
            panelPlatnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 538, Short.MAX_VALUE)
        );
        panelPlatnoLayout.setVerticalGroup(
            panelPlatnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 243, Short.MAX_VALUE)
        );

        tlacitkoLosuj.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tlacitkoLosuj.setText("Losuj");
        tlacitkoLosuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tlacitkoLosujActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setText("Kámen, Nůžky, Papír");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tlacitkoLosuj, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(244, 244, 244))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(panelPlatno, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel1)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(panelPlatno, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tlacitkoLosuj, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tlacitkoLosujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tlacitkoLosujActionPerformed
        index1 = generuj();
        index2 = generuj();
        player1Img = images[index1];
        player2Img = images[index2];
        hodnoceni();
        panelPlatno.repaint();
        
    }//GEN-LAST:event_tlacitkoLosujActionPerformed

public void kresli(Graphics gr){
    System.out.println("Kreslím!");
     //graficky kontext (objekt zodpovedny za vykreslovani) Graphics2D (pretypovani)
        Graphics2D g = (Graphics2D)gr;
        //pomocna metoda pro vyhlazeni car a krivek
        Grafika.antialiasing(g);
        //nastaveni tloustky cary tvaru
        g.setStroke(new BasicStroke(1)); 
        //nastaveni barvy pro kresleni tvaru
        g.setColor(colorWin); 
        //vykresleni tvaru pomoci metod drawXXXXXX napr drawLine(x1,y1,x2y2)
        if(hodnoceni){
          g.fillRect(xPosition, 0, sirkaPlatna/2, vyskaPlatna);  
        }
        
        g.drawImage(player1Img, 20, 10, sirkaImg, vyskaImg, null);
        g.drawImage(player2Img, 295 + sirkaImg, 10, -sirkaImg, vyskaImg, null);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vzor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vzor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vzor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vzor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vzor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelPlatno;
    private javax.swing.JButton tlacitkoLosuj;
    // End of variables declaration//GEN-END:variables

    private int generuj() {
        return nahoda.nextInt(3);
    }

    private void hodnoceni() {
        if(index1 == index2){
            //remiza
            hodnoceni = false;
            //tlacitkoLosuj.doClick(); remiza se pak neobjeví
        }
        else {
         hodnoceni = true;
         xPosition = (vysledky[index1][index2] == 1) ? 0 : sirkaPlatna/2;  
        }
        
        
    }

}
