/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cviceni;

import java.awt.Graphics;
import java.awt.Graphics2D;


/**
 *
 * @author ag
 */
public class Vzor extends javax.swing.JFrame {
    //Vytvor ukazatele na objekty trid Canvas, Rocket
    
    //vytvor promenne left, right typu boolean
    //promenne pro zjisteni, jestli je klavesa stale stistena
    /**
     * vytvoreni objektu
     */
    public Vzor() {
        initComponents();
        //vytvor objekt tridy Canvas pomoci staticke metody prepareCanvas(panelPlatno)
        
        //vytvor objekt tridy Rocket pomoci konstruktoru new Rocket("src/graphics/raketa.png"); konstruktor potrebuje cestu k obrazku rakety
        
        //umisti raketu na dolu na stred pomoci metody rocketOnStart(canvas) objektu rocket
        //canvas je predavan, aby bylo mozne raketu vykreslt na stred
        
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPlatno = new javax.swing.JPanel(){
            protected void paintComponent(Graphics g){
                super.paintComponent(g);
                //moje kreslici metoda
                kresli(g);
            }
        };
        buttonLeft = new javax.swing.JButton();
        buttonRight = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Raketa");

        panelPlatno.setBackground(new java.awt.Color(255, 255, 255));
        panelPlatno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelPlatno.setPreferredSize(new java.awt.Dimension(280, 250));
        panelPlatno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                panelPlatnoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                panelPlatnoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout panelPlatnoLayout = new javax.swing.GroupLayout(panelPlatno);
        panelPlatno.setLayout(panelPlatnoLayout);
        panelPlatnoLayout.setHorizontalGroup(
            panelPlatnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );
        panelPlatnoLayout.setVerticalGroup(
            panelPlatnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        buttonLeft.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonLeft.setText("Left");
        buttonLeft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonLeftMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonLeftMouseReleased(evt);
            }
        });

        buttonRight.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonRight.setText("Right");
        buttonRight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonRightMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonRightMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelPlatno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonRight, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPlatno, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonRight, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void panelPlatnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_panelPlatnoKeyPressed
        //metoda se vola pri stisknuti libovolne klavesy
        //udalost je spojena s objektem panelu (canvas)
        
        //zjisti, kod stisknute klavesy
        
        
        //zjisti, jestli byla stisknuta sipka vlevo
        //pokud ano, tak nastav promennou left na true
        
        //zjisti, jestli byla stisknuta sipka vpravo
        //pokud ano, tak nastav promennou right na true
        
    }//GEN-LAST:event_panelPlatnoKeyPressed

    private void panelPlatnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_panelPlatnoKeyReleased
        //metoda se vola pri uvolneni libovolne klavesy
        //udalost je spojena s objektem panelu (canvas)
        
        //zjisti, kod stisknute klavesy
        
        
        //zjisti, jestli byla uvolnena sipka vlevo
        //pokud ano, tak nastav promennou left na false
        
        //zjisti, jestli byla uvolnena sipka vpravo
        //pokud ano, tak nastav promennou right na false
        
    }//GEN-LAST:event_panelPlatnoKeyReleased

    private void buttonRightMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRightMousePressed
        //metoda se vola pri stisknuti mysi na tlacitku Right
        //zjsti, jestli bylo stisknuto leve tlacitko mysi (hodnota pro leve tlacitko je 1)
        //pokud ano, tak nastav right na true
        
    }//GEN-LAST:event_buttonRightMousePressed

    private void buttonRightMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRightMouseReleased
        //metoda se vola pri uvolneni mysi na tlacitku Right
        //pokud ano, tak nastav right na false
        
        //nastav requestFocus na objektu canvas; nutne, aby fungovaly sipky
        
    }//GEN-LAST:event_buttonRightMouseReleased

    private void buttonLeftMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLeftMousePressed
        //metoda se vola pri stisknuti mysi na tlacitku Left
        //zjsti, jestli bylo stisknuto leve tlacitko mysi (hodnota pro leve tlacitko je 1)
        //pokud ano, tak nastav left na true
        
    }//GEN-LAST:event_buttonLeftMousePressed

    private void buttonLeftMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLeftMouseReleased
        //metoda se vola pri uvolneni mysi na tlacitku Left
        //pokud ano, tak nastav left na false
        
        //nastav requestFocus na objektu canvas; nutne, aby fungovaly sipky
        
    }//GEN-LAST:event_buttonLeftMouseReleased

public void kresli(Graphics gr){
    //System.out.println("Kreslím!");
     //Graphics2D
     Graphics2D g = (Graphics2D)gr;
     
     //jestli je left true, pak nastav posun rakety o hodnotu, kterou vrati metoda getDeltaS
     //zamez, aby raketa nemohla opustit platno
        
        //jestli je right true, pak nastav posun rakety o hodnotu, kterou vrati metoda getDeltaS
        //zamez, aby raketa nemohla opustit platno
        
     //vykresli raketu pomoci metody drawRocket objektu rocket   
     
     
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vzor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vzor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vzor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vzor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vzor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLeft;
    private javax.swing.JButton buttonRight;
    private javax.swing.JPanel panelPlatno;
    // End of variables declaration//GEN-END:variables

    
    private int getDeltaS() {
        //dopln kod pro vypocet drahy posunu; rocket.getSpeed() * canvas.getTimerDelay()/1000f;
        //metoda musi vracet int; vyuzoj Math.round()
        return 0;
    }
}
