/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cviceni;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import tvary.Bod;

/**
 *
 * @author ag
 */
public class Vzor extends javax.swing.JFrame {
    private Bod levyHorni, pravyDolni, stredPlatna;
    private int delkaObdelnika, vyskaObdelnika, sirkaPlatna, vyskaPlatna;
    /**
     * Creates new form Tecka
     */
    public Vzor() {
        initComponents();
        //kontrolni vypis vysky a sirky platna
        sirkaPlatna = panelPlatno.getWidth();
        vyskaPlatna = panelPlatno.getHeight();
        System.out.println("Šířka: " + sirkaPlatna);//pomocny vypis
        System.out.println("Výška: " + vyskaPlatna);//pomocny vypis
        
        //nastaveni levyHorni bod, delka a sirka; natsaveni na stred
        stredPlatna = new Bod(sirkaPlatna/2,vyskaPlatna/2);
        levyHorni = new Bod(0,0);
        obdelnikNaStred(); //volani metody, ktera umisti obdelnik na stred
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPlatno = new javax.swing.JPanel(){
            protected void paintComponent(Graphics g){
                super.paintComponent(g);
                //moje kreslici metoda
                kresli(g);
            }
        };
        tlacitkoPrekresli = new javax.swing.JButton();
        labelX = new javax.swing.JLabel();
        textFieldX = new javax.swing.JTextField();
        labelY = new javax.swing.JLabel();
        textfieldY = new javax.swing.JTextField();
        fieldDelka = new javax.swing.JTextField();
        labelDelka = new javax.swing.JLabel();
        labelVyska = new javax.swing.JLabel();
        fieldVyska = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kreslení");

        panelPlatno.setBackground(new java.awt.Color(255, 255, 255));
        panelPlatno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelPlatno.setPreferredSize(new java.awt.Dimension(280, 250));

        javax.swing.GroupLayout panelPlatnoLayout = new javax.swing.GroupLayout(panelPlatno);
        panelPlatno.setLayout(panelPlatnoLayout);
        panelPlatnoLayout.setHorizontalGroup(
            panelPlatnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );
        panelPlatnoLayout.setVerticalGroup(
            panelPlatnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 248, Short.MAX_VALUE)
        );

        tlacitkoPrekresli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tlacitkoPrekresli.setText("Překresli");
        tlacitkoPrekresli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tlacitkoPrekresliActionPerformed(evt);
            }
        });

        labelX.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelX.setText("X:");

        textFieldX.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textFieldX.setText("0");
        textFieldX.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelY.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelY.setText("Y:");

        textfieldY.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textfieldY.setText("0");
        textfieldY.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        fieldDelka.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        fieldDelka.setText("0");
        fieldDelka.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelDelka.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelDelka.setText("délka:");

        labelVyska.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelVyska.setText("výška:");

        fieldVyska.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        fieldVyska.setText("0");
        fieldVyska.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelVyska)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelDelka)
                                .addComponent(labelX, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(labelY, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textfieldY)
                            .addComponent(fieldDelka)
                            .addComponent(fieldVyska)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(textFieldX, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tlacitkoPrekresli)))
                .addGap(18, 18, 18)
                .addComponent(panelPlatno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldX, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelX))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textfieldY, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelY))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldDelka, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDelka))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldVyska, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelVyska))
                        .addGap(22, 22, 22)
                        .addComponent(tlacitkoPrekresli, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelPlatno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tlacitkoPrekresliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tlacitkoPrekresliActionPerformed
        panelPlatno.repaint();
    }//GEN-LAST:event_tlacitkoPrekresliActionPerformed

public void kresli(Graphics gr){
    System.out.println("Kreslím!");
     //graficky kontext (objekt zodpovedny za vykreslovani) Graphics2D (pretypovani)
     Graphics2D g = (Graphics2D) gr;
        //nastaveni tloustky cary tvaru
        g.setStroke(new BasicStroke(5));//nastaveni tloustky cary (bodu na 5)
        //nastaveni barvy pro kresleni tvaru
        //****dopln metodu pro barvu bodu****
        g.setColor(Color.red);
        //ziskej souradnice, kde se ma levyHorni vykreslit (vytvor metodu, ktera souradnice ziska a overi, jestli jsou na platne)
        //getCoordinates();
        //vykresleni tvaru pomoci metod drawXXXXXX napr drawLine(x1,y1,x2y2); pozij pro souradnice metody setX a setY objektu levyHorni
        g.fillRect(levyHorni.getX(), levyHorni.getY(), delkaObdelnika, vyskaObdelnika);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vzor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vzor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vzor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vzor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vzor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldDelka;
    private javax.swing.JTextField fieldVyska;
    private javax.swing.JLabel labelDelka;
    private javax.swing.JLabel labelVyska;
    private javax.swing.JLabel labelX;
    private javax.swing.JLabel labelY;
    private javax.swing.JPanel panelPlatno;
    private javax.swing.JTextField textFieldX;
    private javax.swing.JTextField textfieldY;
    private javax.swing.JButton tlacitkoPrekresli;
    // End of variables declaration//GEN-END:variables

    private void getCoordinates() {
       int x,y;
       x = Integer.parseInt(textFieldX.getText()); //chybi osetreni chybneho zadani
       y = Integer.parseInt(textfieldY.getText());
       
       if((x < 0 || x > panelPlatno.getWidth()) || (y < 0 || y > panelPlatno.getHeight())){
           obdelnikNaStred();
       }
       else{
          //nastaveni souradnic na nove hodnoty zadane utivatelem
           levyHorni.setX(x);
           levyHorni.setY(y); 
       }
       
    }
    
    private void obdelnikNaStred(){
        //nastaveni delky a vysky obdelnika
          delkaObdelnika = 150;
          vyskaObdelnika = 60;
        //nastaveni souradnic levehoHorniho bodu
          levyHorni.setX(stredPlatna.getX()-delkaObdelnika/2);
          levyHorni.setY(stredPlatna.getY()-vyskaObdelnika/2); 
         //levyHorni = new Bod(stredPlatna.getX()-delkaObdelnika/2,stredPlatna.getY()-vyskaObdelnika/2);   
        //hodnoty v polich fieldX a fieldY nastaveny na stred
           //fieldX.setText(String.valueOf(stred.getX()));
           //fieldY.setText(String.valueOf(stred.getY()));   
    }

}
